### ISSUE TITLE
Disable on_success email notification in Travis CI configuration

### ISSUE THREAD

**Issue by raphaelstolt** [jonathantorres/construct#198]
To reduce the noise coming from email notifications for Travis CI builds, a possible configuration might look like:
```yaml
notifications:
  email:
    on_success: never # default: change
    on_failure: always # default: always
```
